### ISSUE TITLE
Mariadb

### ISSUE THREAD

**Issue by netnut404** [Auhrus/fivem-docker-server#5]
**Describe your proposal as best you can.**
most the features when trying to deploy require mysql / Mariadb.
would it be possible to add that to your docker image?

**Comment by Auhrus** [comment]
Hello, I would like to keep the image as small as possible and only add the essentials for the server, especially since not everyone who uses this image needs an SQL server and that would be an unnecessary load for those in the background. So I don't put mysql or mariadb directly into the image.
However, you can either create a second container which provides the DB and connect the two containers with each other via networking. Example:
```bash
docker network create -d bridge --internal --scope=local --subnet 192.168.133.1/26 --gateway 192.168.133.1 sql_connection \

docker run -d -t --name eminent-shade-fivem -p 40120:40120/tcp -p 30120:30120/tcp -p 30120:30120/udp -e download=VERSION -v VOLUME_NAME:/opt/fivem/txData --network sql_connection --network bridge ghcr.io/auhrus/fivem:latest \

docker create --name eminent-shade-mariadb -v /opt/mariadb:/var/lib/mysql -p 3306:3306/tcp -e MARIADB_ROOT_PASSWORD=password --restart always --network sql_connection --ip 192.168.1.10 docker.io/mariadb:latest
```
The IP of the mariaDB will be: 192.168.1.10
On the other hand, you could also connect the two containers via Docker Compose. Example:

```yml
version: "3.4"
services:

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    container_name: eminent-shade-mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: your_root_password

  fivem:
    image: ghcr.io/auhrus/fivem:latest
    restart: unless-stopped
    container_name: eminent-shade-fivem
    environment:
      download: version_link
      TZ: tz
    ports:
      - "30120:30120/tcp"
      - "30120:30120/udp"

volumes:
  mariadb_data:
```
The IP of the mariaDB will be: mariadb
